sudo: required
dist: trusty
language: cpp

before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
  - sudo apt-get -qq update
  - sudo apt-get install -y libboost-dev libboost-test-dev libboost-python-dev python-numpy python3-numpy libpython3-dev swig doxygen fftw3-dev libeigen3-dev libpython3-dev
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libboost_python-py34.so /usr/lib/x86_64-linux-gnu/libboost_python3.so

script:
  - mkdir build
  - cd build
  - cmake -DPYTHON_EXECUTABLE=$PYTHON .. && make && make test ARGS="-V"
  - make doc

env:
  - PYTHON=/usr/bin/python
  - PYTHON=/usr/bin/python3

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: enable-travis
  local_dir: html
